name: Builds

on:
  push:
  pull_request:
    branches:
      - master
      - 'release/**'

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install libeigen3-dev

    - name: Initialize Submodules      
      run: cd $GITHUB_WORKSPACE; git submodule update --init
       
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DALGEBRA_PLUGIN_INCLUDE_EIGEN=On -DCMAKE_BUILD_TYPE=Release 

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Unit Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C Release

  ubuntu_float:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install libeigen3-dev

    - name: Initialize Submodules      
      run: cd $GITHUB_WORKSPACE; git submodule update --init
       
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DALGEBRA_PLUGIN_INCLUDE_EIGEN=On -DDALGEBRA_PLUGIN_CUSTOM_SCALARTYPE=float

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Unit Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C Release

  ubuntu_debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install libeigen3-dev

    - name: Initialize Submodules      
      run: cd $GITHUB_WORKSPACE; git submodule update --init
       
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DALGEBRA_PLUGIN_INCLUDE_EIGEN=On

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Debug

    - name: Unit Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C Debug

  macos:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: brew install cmake eigen ninja

    - name: Initialize Submodules      
      run: cd $GITHUB_WORKSPACE; git submodule update --init
       
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DALGEBRA_PLUGIN_INCLUDE_EIGEN=On

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Unit Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C Release